name: Android APK Build

on:
  push:
    tags:
      - 'v*' # Trigger only when a new tag matching the pattern 'v*' is pushed

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./GooberEats
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build APK with Gradle
      run: ./gradlew assembleRelease
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-release.apk
        if-no-files-found: error
        overwrite: true
        path: ./app/build/outputs/apk/release/*
